### PR TITLE
Boarding summaries for acceptance criteria

### PR DESCRIPTION
**Pull request by DavidOry**
@shimonisrael 

Here is some R code to do some simple reductions of the on-board survey for our use in the travel model acceptance criteria. Please review as time allows and let me know if you have any comments. Thank you.

fyi @lmz, @FlaviaTsang

### CODE REVIEW

**Comment by lmz** [comment]
Why Rmd rather than R? 🤔

**Comment by DavidOry** [comment]
> Why Rmd rather than R? 🤔

How about NO GOOD REASON? :) 

Replaced with R.

**Comment by shimonisrael** [comment]
@DavidOry, returning to this. Two things: there's a more recent dataset I can share that has the PopulationSim weights and more operators; and SMART isn't in the any of the consolidated datasets because they all have a base year of 2015 and SMART service began in 2017. I can share the raw data from the SMART survey if that's desirable.

**Comment by DavidOry** [comment]
> @DavidOry, returning to this. Two things: there's a more recent dataset I can share that has the PopulationSim weights and more operators; and SMART isn't in the any of the consolidated datasets because they all have a base year of 2015 and SMART service began in 2017. I can share the raw data from the SMART survey if that's desirable.

Thanks Shimon. Yes, a newer survey would be great. SMART is not critical given our primary validation year will be 2015, as you say.

**Pull request merged**
