### PR TITLE
Refactor with Canonical Route Name Database

### PR DESCRIPTION
**Pull request by jhelsel11**
This code began on the transitland_database branch, but is being moved to a new branch because transitland did not work out. See Canonical Route Names - OLD DISCUSSION for pull request comments prior to the new name.

### CODE REVIEW

**Comment by jhelsel11** [comment]
@DavidOry I've made a first pass at changing "BART" to the boarding and alighting stations. It works for a very limited case (one set of lat/long coordinates for BART only for the SF Muni survey), but I think I can turn it into a function and handle more use cases. In my mind the next steps for this effort are:
1) Turn lines 565 to 643 of standard_route_name_db.R into a function that takes strings as inputs to handle each of the route legs.
2) Go through the minimum distance calculation. Right now more than half of the minimum distances between boarding or alighting lat/long are more than 5000 meters. Something has clearly gone wrong given what the stations look like when they're actually mapped. If we want to keep this in simple features, I'll have to dive more deeply into the st_distance function. Alternatively, the coordinates can be brought out of sfc objects, and we do a cartesian distance calculation directly on the coordinates.
3) The BART replacement with station names needs to be moved prior to the code creating the canonical names.
4) The canonical names code needs to be redone to handle the new BART station names.
5) The minimum distance code needs to handle all use cases for sf_muni, caltrain, bart, and ac_transit surveys.

**Comment by jhelsel11** [comment]
The nearest neighbor analysis seems to be working as intended. I inspected a map of the boardings overlaid with the canonical stations provided by @shimonisrael. The BART stations are being correctly labeled. I also tested the distances with a haversine function (in geospheres) and the distances are much smaller than those reported by the simple features program (e.g. trip 22485 in the muni survey came back as being 10.5 km from the Richmond station but the haversine function (and inspection within qgis) shows that it is really about 127 meters). I would recommend that I drop the distance calculation and proceed with the naming as I turn this into a function.

**Comment by jhelsel11** [comment]
@DavidOry Please review the functions get_nearest_station and get_rail_names (lines 65-154) of standard_route_db.R. I think these functions capture 90% of the eventual capabilities we'll need, but I think it would be a good idea for someone else to take a look and QAQC since this will play such an important role in the processing.

**Comment by DavidOry** [comment]
In the below (lines 88 to 92), we should be filtering the universe of stations by operator, no? For example, BART and Caltrain both stop at Millbrae, but we want the BART records associated with BART, not Caltrain. 

```
   closest_neighbor <-  data.frame(index = 0) 
   closest_neighbor <- closest_neighbor %>% 
     filter(index !=0) 

   distances <- route_df %>% 
     st_distance(station_names)
```

**Comment by DavidOry** [comment]
I like the idea of just using Cartesian geography (with the minor addition of acknowledging the sphere with the Haversine). That would allow the script to be larger free of the spatial packages, which I've never found to be particularly robust over time.

**Comment by jhelsel11** [comment]
> In the below (lines 88 to 92), we should be filtering the universe of stations by operator, no? For example, BART and Caltrain both stop at Millbrae, but we want the BART records associated with BART, not Caltrain.
> 
> ```
>    closest_neighbor <-  data.frame(index = 0) 
>    closest_neighbor <- closest_neighbor %>% 
>      filter(index !=0) 
> 
>    distances <- route_df %>% 
>      st_distance(station_names)
> ```

I haven't begun the task of handling multiple operators. Everything is currently hard coded to only handle BART. If I'm getting BART right, then I'll start work on Caltrain (all within Muni for the moment; I'll also need to update the bespoke code below within the more general Muni processing).

**Comment by DavidOry** [comment]
Can we execute the below code without the `for` loop. I've not 

> In the below (lines 88 to 92), we should be filtering the universe of stations by operator, no? For example, BART and Caltrain both stop at Millbrae, but we want the BART records associated with BART, not Caltrain.
>    closest_neighbor <-  data.frame(index = 0) 
>    closest_neighbor <- closest_neighbor %>% 
>      filter(index !=0) 
> 
>    distances <- route_df %>% 
>      st_distance(station_names)
> 
> 
> I haven't begun the task of handling multiple operators. Everything is currently hard coded to only handle BART. If I'm getting BART right, then I'll start work on Caltrain.

Right. But if you're universe is BART, why not filter `station_names` to only look at BART stations when you find the minimum distance?

**Comment by jhelsel11** [comment]
> Can we execute the below code without the `for` loop. I've not
> 
> > In the below (lines 88 to 92), we should be filtering the universe of stations by operator, no? For example, BART and Caltrain both stop at Millbrae, but we want the BART records associated with BART, not Caltrain.
> > closest_neighbor <-  data.frame(index = 0)
> > closest_neighbor <- closest_neighbor %>%
> > filter(index !=0)
> > distances <- route_df %>%
> > st_distance(station_names)
> > I haven't begun the task of handling multiple operators. Everything is currently hard coded to only handle BART. If I'm getting BART right, then I'll start work on Caltrain.
> 
> Right. But if you're universe is BART, why not filter `station_names` to only look at BART stations when you find the minimum distance?

That could work. I will need to look at whether Shimon's shape file says which stations are BART and which are Caltrain and which are shared. The lat/longs (within Muni, anyway) are smack on top of one station or another, so I'm not too worried about grabbing the right station.

I can look into replacing the for loop with a group by statement of some kind. The distances data structure and its indexing is a little finicky with the tidyverse syntax.

**Comment by DavidOry** [comment]
Could be another reason to get rid of the `st_distance` measure. It would seem you could do a full join to pair every BART station (in `station_name`) with every BART survey record. Then compute the Haversine distance from the coordinates. And then take the minimum distance for each group, where the survey record ID keys the groups. This might be faster and cleaner.

**Comment by DavidOry** [comment]
Probably better to ask @shimonisrael for a shape file that does contain the operator name (i.e., BART rather than 'Rapid Rail') and build a workflow around that. @shimonisrael: if such a shape file is readily available, can you please provide? Meaning, same as before, but with the operator name appended to each station in addition to the technology.

**Comment by shimonisrael** [comment]
> 
> 
> Probably better to ask @shimonisrael for a shape file that does contain the operator name (i.e., BART rather than 'Rapid Rail') and build a workflow around that. @shimonisrael: if such a shape file is readily available, can you please provide? Meaning, same as before, but with the operator name appended to each station in addition to the technology.

I'll take a look. Working from home today, and this may require me checking in with Kearey's staff, so could be tomorrow.

**Comment by shimonisrael** [comment]
Doesn't the field "agencyname" provide the operator? I thought I'd initially forwarded John this one, but perhaps I'm wrong:
https://mtc.maps.arcgis.com/home/item.html?id=efd75b7bb3c04dbda06c6e7cd73e9336

**Comment by jhelsel11** [comment]
> Doesn't the field "agencyname" provide the operator? I thought I'd initially forwarded John this one, but perhaps I'm wrong:
> https://mtc.maps.arcgis.com/home/item.html?id=efd75b7bb3c04dbda06c6e7cd73e9336

I can make this file work. I mistook agency name for the owner of the station with nonexclusive access rights (and thought the ability to transfer would need another file).

**Comment by DavidOry** [comment]
Here's a code snippet for the approach I described for `get_nearest_station`, fwiw.

```
  # testing names
  station_names_df <- station_names
  survey_records_df <- survey_records
  route_name_string <- "final_trip_to_first_route"
  lat_name_string <- "final_transfer_to_first_boarding_lat"
  lon_name_string <- "final_transfer_to_first_boarding_lon"
  
  operator_key_string <- "BART"
  temp_tech_key_string <- "Rapid Rail"
  
  # function
  vars <- c(route = route_name_string,
            lat = lat_name_string,
            lng = lon_name_string)
  
  relevant_records_df <- survey_records_df %>%
    select(id, vars) %>%
    filter(str_detect(route, operator_key_string)) %>%
    mutate(lat = as.numeric(lat),
           lng = as.numeric(lng))
  
  relevant_stations_df <- station_names_df %>%
    filter(mode == temp_tech_key_string) %>%
    sfc_as_cols(., st_geometry(.), c("sta_lon", "sta_lat")) %>%
    select(index, sta_lon, sta_lat)
  
  st_geometry(station_names_df) <- NULL
  st_geometry(relevant_stations_df) <- NULL
  
  working_df <- merge(relevant_records_df, relevant_stations_df) %>%
    mutate(distance_meters = mapply(function(r_lng, r_lat, s_lng, s_lat)
      distm(c(r_lng, r_lat), c(s_lng, s_lat), fun = distHaversine), lng, lat, sta_lon, sta_lat))
  
  return_df <- working_df %>%
    group_by(id) %>%
    summarise(min_distance = min(distance_meters)) %>%
    ungroup() %>%
    left_join(., relevant_records_df, by = c("id")) %>%
    left_join(., select(working_df, id, index, distance_meters), by = c("id", "min_distance" = "distance_meters")) %>%
    left_join(., station_names_df, by = c("index"))
    
  
  return(return_df)
```

**Comment by DavidOry** [comment]
I use this [helper method ](https://github.com/r-spatial/sf/issues/231)to get the coordinates from the SF Point object:

```
sfc_as_cols <- function(x, geometry, names = c("x","y")) {
  if (missing(geometry)) {
    geometry <- sf::st_geometry(x)
  } else {
    geometry <- rlang::eval_tidy(enquo(geometry), x)
  }
  stopifnot(inherits(x,"sf") && inherits(geometry,"sfc_POINT"))
  ret <- sf::st_coordinates(geometry)
  ret <- tibble::as_tibble(ret)
  stopifnot(length(names) == ncol(ret))
  x <- x[ , !names(x) %in% names]
  ret <- setNames(ret,names)
  dplyr::bind_cols(x,ret)
}
```

**Comment by jhelsel11** [comment]
> Here's a code snippet for the approach I described for `get_nearest_station`, fwiw.
> 
> ```
>   # testing names
>   station_names_df <- station_names
>   survey_records_df <- survey_records
>   route_name_string <- "final_trip_to_first_route"
>   lat_name_string <- "final_transfer_to_first_boarding_lat"
>   lon_name_string <- "final_transfer_to_first_boarding_lon"
>   
>   operator_key_string <- "BART"
>   temp_tech_key_string <- "Rapid Rail"
>   
>   # function
>   vars <- c(route = route_name_string,
>             lat = lat_name_string,
>             lng = lon_name_string)
>   
>   relevant_records_df <- survey_records_df %>%
>     select(id, vars) %>%
>     filter(str_detect(route, operator_key_string)) %>%
>     mutate(lat = as.numeric(lat),
>            lng = as.numeric(lng))
>   
>   relevant_stations_df <- station_names_df %>%
>     filter(mode == temp_tech_key_string) %>%
>     sfc_as_cols(., st_geometry(.), c("sta_lon", "sta_lat")) %>%
>     select(index, sta_lon, sta_lat)
>   
>   st_geometry(station_names_df) <- NULL
>   st_geometry(relevant_stations_df) <- NULL
>   
>   working_df <- merge(relevant_records_df, relevant_stations_df) %>%
>     mutate(distance_meters = mapply(function(r_lng, r_lat, s_lng, s_lat)
>       distm(c(r_lng, r_lat), c(s_lng, s_lat), fun = distHaversine), lng, lat, sta_lon, sta_lat))
>   
>   return_df <- working_df %>%
>     group_by(id) %>%
>     summarise(min_distance = min(distance_meters)) %>%
>     ungroup() %>%
>     left_join(., relevant_records_df, by = c("id")) %>%
>     left_join(., select(working_df, id, index, distance_meters), by = c("id", "min_distance" = "distance_meters")) %>%
>     left_join(., station_names_df, by = c("index"))
>     
>   
>   return(return_df)
> ```

Do you expect the tech to be an important parameter? I thought the only two services that needed replacing were generic BART and Caltrain entries, which should all be heavy/rapid rail.

**Comment by jhelsel11** [comment]
> Here's a code snippet for the approach I described for `get_nearest_station`, fwiw.
> 
> ```
>   # testing names
>   station_names_df <- station_names
>   survey_records_df <- survey_records
>   route_name_string <- "final_trip_to_first_route"
>   lat_name_string <- "final_transfer_to_first_boarding_lat"
>   lon_name_string <- "final_transfer_to_first_boarding_lon"
>   
>   operator_key_string <- "BART"
>   temp_tech_key_string <- "Rapid Rail"
>   
>   # function
>   vars <- c(route = route_name_string,
>             lat = lat_name_string,
>             lng = lon_name_string)
>   
>   relevant_records_df <- survey_records_df %>%
>     select(id, vars) %>%
>     filter(str_detect(route, operator_key_string)) %>%
>     mutate(lat = as.numeric(lat),
>            lng = as.numeric(lng))
>   
>   relevant_stations_df <- station_names_df %>%
>     filter(mode == temp_tech_key_string) %>%
>     sfc_as_cols(., st_geometry(.), c("sta_lon", "sta_lat")) %>%
>     select(index, sta_lon, sta_lat)
>   
>   st_geometry(station_names_df) <- NULL
>   st_geometry(relevant_stations_df) <- NULL
>   
>   working_df <- merge(relevant_records_df, relevant_stations_df) %>%
>     mutate(distance_meters = mapply(function(r_lng, r_lat, s_lng, s_lat)
>       distm(c(r_lng, r_lat), c(s_lng, s_lat), fun = distHaversine), lng, lat, sta_lon, sta_lat))
>   
>   return_df <- working_df %>%
>     group_by(id) %>%
>     summarise(min_distance = min(distance_meters)) %>%
>     ungroup() %>%
>     left_join(., relevant_records_df, by = c("id")) %>%
>     left_join(., select(working_df, id, index, distance_meters), by = c("id", "min_distance" = "distance_meters")) %>%
>     left_join(., station_names_df, by = c("index"))
>     
>   
>   return(return_df)
> ```

I've looked through the code snippet. The non-loop approach takes 21 seconds and my loop is 1.08 seconds.

**Comment by DavidOry** [comment]
Re: the tech is just a placeholder. It should be replaced with the operator name to narrow the range of potential matches per our previous discussion.

I think in this case runtime << important than readability and avoidance of reliance on shaking packages. I'm okay with the for loop provided the code is easy to read.

**Comment by jhelsel11** [comment]
The haversine distance function is getting some odd results. When I run the sf_muni routes for caltrain, they come back with station matches that are more than 1km away. I need to investigate whether there are other stations at the locations and there's a problem with attributing them to Caltrain or whether there's something else wrong. (I also looked at BART routes for AC Transit and they're failing the distance check.)

**Comment by jhelsel11** [comment]
@DavidOry 
I'm creating a method to handle renaming routes to a set of standard names. In the script I developed independently I separated the operator from the route (e.g. "AC 623 to Irvington High School, Horner Jr." becomes operator "AC Transit" and route "623 to Irvington High School, Horner Jr.". To make this scheme work in the build standard database markdown I'm adding columns for the operator for each transfer.

**Comment by DavidOry** [comment]
Really good progress @jhelsel11. I think this organization is much better. Let me know when it's ready for me to test and/or code review more closely. Thanks!

**Comment by jhelsel11** [comment]
@DavidOry I'll give an update when we speak today. I think the script order is all working as of the latest commit. However, I'm chasing down 3 errors in the crosswalk.
1) There's a stanford shuttle the caltrain survey that wasn't properly processed
2) There seems to be some missing VTA routes in the Muni survey
3) The way I'm handling Caltrain routes in the BART survey is broken. This may end up requiring reordering the function calls?

**Comment by DavidOry** [comment]
@jhelsel11: Please add the route technology (e.g., local bus, light rail) to the `canonical_route_crosswalk.csv` and use this to define the technology. We can then replace the `survey_tech_update` step and remove the `bespoke_survey_tech_replacement.csv` database.

**Comment by jhelsel11** [comment]
@DavidOry will keep looking at this, but we should weigh the convenience of having all of the nonconforming routes in a single list versus having them be distributed throughout a regular expressions procedure.

**Comment by jhelsel11** [comment]
@DavidOry 
In the process of moving the technology over to the canonical route crosswalk. I was thinking about it the wrong way. But, I do have 2 questions.
1) Should I stick with the technology list of "commuter rail, express bus, ferry, heavy rail, & local bus"? What is the difference you're postulating between heavy rail and commuter rail? I just want to make I understand the distinction in case it crops up in other parts of the Rmd.
2) The method in the Rmd has 26 operators. Because @shimonisrael asked me to keep more information in the operators (e.g. the shuttle operators), there are now 54. Shouldn't cause a problem as most of them are either ferries or local bus, but it's long enough I'm thinking of moving it to yet another csv that would be read in.

**Comment by DavidOry** [comment]
@jhelsel11:
1. Yes, the universe of technologies should be commuter rail, express bus, ferry, heavy rail, and local bus. The primary purpose of tagging the technology is for comparisons to the travel model, and these are the technology categories the technology uses.

2. If the technology is added to the canonical database, wouldn't we then be able to remove the `set_base_technology` method (as well as the `update_technology` and then remove the technology argument in the `read_operator` method)?

**Comment by jhelsel11** [comment]
@DavidOry can you look at the comments in step 5 of the RMD? I'm not sure what the appropriate conditions are for applying the missing conditions. (Have they been changed with the geocoding for BART routes?)

**Comment by jhelsel11** [comment]
@DavidOry I've found a bug inside the function that assigns BART/Caltrain station locations. There are numerous records in AC Transit and SF Muni where the first transfer after alighting is on BART/Caltrain but that act is not properly geocoded. (As an example look at record 10018 in AC Transit.) I will investigate further tomorrow.

**Comment by jhelsel11** [comment]
> @DavidOry I've found a bug inside the function that assigns BART/Caltrain station locations. There are numerous records in AC Transit and SF Muni where the first transfer after alighting is on BART/Caltrain but that act is not properly geocoded. (As an example look at record 10018 in AC Transit.) I will investigate further tomorrow.

This issue is solved.

**Comment by jhelsel11** [comment]
@DavidOry, I have updated the tech assignment portion of the script and the RMD is ready for your review. I will continue working on the parallel tasks assigned to me within Asana.

**Comment by DavidOry** [comment]
@jhelsel11: why are the Caltrain routes in the canonical database but the BART routes are not?

**Comment by DavidOry** [comment]
@jhelsel11: please have a look at the changes I made. A few comments and questions:

1. Please avoid using global variables in the methods, e.g., the canonical shape file.

2. Please use suffixes to denote the data types in the methods, e.g., "_df", as is makes it easier to debug.

3. Please use a different delimiter to separate the operator from the route than from the station-to-station name in the BART and Caltrain routes.  For, example, change BART___Station A___Station_B to BART___Station A --- Station B. This allows for easier separation of the operator from the route name (i.e., ____ will only appear once).

4. Your operator extraction (below) fails. See, e.g., "TRI-DELTA". Please correct.

```
survey_standard <- survey_standard %>%
  mutate(first_before_operator = str_extract(first_route_before_survey_board, "^[A-z ]+?(?=_)"),
         second_before_operator = str_extract(second_route_before_survey_board, "^[A-z ]+?(?=_)"),
         third_before_operator = str_extract(third_route_before_survey_board, "^[A-z ]+?(?=_)"),
         first_after_operator = str_extract(first_route_after_survey_alight, "^[A-z ]+?(?=_)"),
         second_after_operator = str_extract(second_route_after_survey_alight, "^[A-z ]+?(?=_)"),
         third_after_operator = str_extract(third_route_after_survey_alight, "^[A-z ]+?(?=_)"))
```

5. Please have a look at and check the balance of my changes to make sure I didn't mess anything up. 

thanks.

**Comment by jhelsel11** [comment]
> @jhelsel11: why are the Caltrain routes in the canonical database but the BART routes are not?

@DavidOry 

I believe they were at one point, but I was heading down a path where I asked about creating an intermediate bart file that would hold the created routes. I was told not to do that so I removed the code creating the bart routes. The caltrain information isn't actually used anywhere (currently), because the caltrain names are generated in the geocoding script in the RMD. (And the bart/caltrain names are generated again for their respective surveys in the RMD.)

I will add the bart routes back in in the interest of having a complete listing of the canonical routes. I will also do some work in that list to ensure the canonical rail route names are consistent with the naming conventions used elsewhere. However, they will not (currently) be consistent with the names from the canonical shape file since I've removed non alpha-numeric characters from the canonical names list.

**Comment by DavidOry** [comment]
I've added the BART names to the canonical db in my recent commit. Please use the canonical DB to build the cross-walk between the canonical names (i.e., those in the shape file) and the names in the BART survey (the RMD creates a route name from the on and off stations).

**Comment by jhelsel11** [comment]
> I've added the BART names to the canonical db in my recent commit. Please use the canonical DB to build the cross-walk between the canonical names (i.e., those in the shape file) and the names in the BART survey (the RMD creates a route name from the on and off stations).

Do you have the script that generated the BART names in the canonical db? Otherwise those names will be removed the next time the canonical db script is run (since there's a write_csv command at the end of the script)

**Comment by DavidOry** [comment]
>           > I've added the BART names to the canonical db in my recent commit. Please use the canonical DB to build the cross-walk between the canonical names (i.e., those in the shape file) and the names in the BART survey (the RMD creates a route name from the on and off stations).
> 
> 
> Do you have the script that generated the BART names in the canonical db? Otherwise those names will be removed the next time the canonical db script is run (since there's a write_csv command at the end of the script)

Ah. I just took the unique set of routes from the BART survey. Perhaps you can write that out as a CSV file that is consumed by the canonical DB generator?

**Comment by jhelsel11** [comment]
Next step after return from New Year's:
1) start at line 1272 in the Rmd.
2) recreate geocoding steps, should effectively be replacing TAP nearest neighbor code (point to point) with dest/home/school/work nearest to TAZ nearest neighbor (point to poly).

**Comment by DavidOry** [comment]
@shimonisrael: Please have a look at the code. @jhelsel11 is now working on the geo-coding piece, but that should not require meaningful changes to the user experience.

**Comment by shimonisrael** [comment]
> 
> 
> @shimonisrael: Please have a look at the code. @jhelsel11 is now working on the geo-coding piece, but that should not require meaningful changes to the user experience.

Thanks, Dave. I'll take a look.

**Comment by jhelsel11** [comment]
@DavidOry, do you want survey_standard/survey_flat/etc. to be renamed in line with the _df convention?

**Comment by DavidOry** [comment]
Yes please re: `_df`.

**Pull request merged**
